mas/guesswho/urls.py
from django.conf.urls import url
from guesswho import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^play/$', views.PlayView.as_view(), name='play'),
    url(r'^play/reset/$', views.reset_game, name='reset'),
    url(r'^play/char/([a-zA-Z]+)/$', views.pick_char, name='char'),
    url(r'^play/question/([a-zA-Z]+)/$', views.question, name='question'),
    url(r'^play/guess/([a-zA-Z]+)/$', views.guess, name='guess'),
]

mas/mas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import guesswho.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(guesswho.urls, namespace='guesswho')),
]

mas/guesswho/models.py
from django.db import models

# Create your models here.

mas/guesswho/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
import random

characters = {
    'David': ['beard'],
    'Frans': [],
    'Max': ['moustache'],
    'Paul': ['glasses'],
    'Richard': ['bald', 'beard', 'moustache'],
    'Sam': ['bald', 'glasses'],
}

# States of knowledge
NO     = 1
YES    = 2
UNKNOWN = 3

class HomeView(TemplateView):
    template_name = 'home.html'


class PlayView(TemplateView):
    template_name = 'play.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PlayView, self).get_context_data(*args, **kwargs)
        context['chars'] = sorted(characters.keys())
        try:
            context['npc_knows'] = []
            for k, v in self.request.session['npc_knows'].items():
                if v == YES:
                    context['npc_knows'].append(k)
                elif v == NO:
                    context['npc_knows'].append('&not;' + k)
                elif v == UNKNOWN:
                    context['npc_knows'].append(k + ' &#8897; &not;' +  k)

            context['player_knows'] = []
            context['exclude'] = set()
            for k, v in self.request.session['player_knows'].items():
                if v == YES:
                    context['player_knows'].append(k)
                elif v == NO:
                    context['player_knows'].append('&not;' + k)
                elif v == UNKNOWN:
                    context['player_knows'].append(k + ' &#8897; &not;' + k)

                # Find out which characters to grey out
                for name, traits in characters.items():
                    if k in traits and v == NO:
                        context['exclude'].add(name)
                    elif k not in traits and v == YES:
                        context['exclude'].add(name)
            context['exclude'] = list(context['exclude']) + \
                self.request.session['exclude_extra']
            context['questions'] = reversed(self.request.session['questions'])
        except KeyError:
            context['npc_knows'] = None
            context['player_knows'] = None
            context['exclude'] = None
            context['questions'] = None
        return context


def reset_game(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('guesswho:play'))

def pick_char(request, name):
    if name in characters.keys():
        request.session['char'] = name
        request.session['npc_char'] = random.choice(list(characters.keys()))
        request.session['npc_knows'] = {
            'bald': UNKNOWN,
            'beard': UNKNOWN,
            'glasses': UNKNOWN,
            'moustache': UNKNOWN,
        }
        request.session['player_knows'] = {
            'bald': UNKNOWN,
            'beard': UNKNOWN,
            'glasses': UNKNOWN,
            'moustache': UNKNOWN,
        }
        request.session['npc_possible'] = list(characters.keys())
        request.session['questions'] = []
        request.session['exclude_extra'] = []
        request.session['finished'] = False
    else:
        messages.warning(request, 'This is not a valid character')
    return HttpResponseRedirect(reverse('guesswho:play'))

def guess(request, name):
    question = 'You: is it ' + name + '?'
    request.session['questions'].append(question)
    if request.session['npc_char'] == name:
        request.session['questions'].append('Computer: Yes')
        request.session['questions'].append("You've won")
        request.session['finished'] = True
        request.session['exclude_extra'] = list(characters.keys())
        request.session['exclude_extra'].remove(name)
    else:
        request.session['questions'].append('Computer: No')
        request.session['exclude_extra'].append(name)
        computer_turn(request)

    request.session.modified = True
    return HttpResponseRedirect(reverse('guesswho:play'))

def get_question_text(subject):
    if subject == 'bald':
        return 'Is he bald?'
    elif subject == 'beard':
        return 'Does he have a beard?'
    elif subject == 'glasses':
        return 'Does he wear glasses?'
    elif subject == 'moustache':
        return 'Does he have a moustache?'

def question(request, subject):
    question = 'You: ' + get_question_text(subject)
    request.session['questions'].append(question)

    if subject in characters[request.session['npc_char']]:
        question = 'Computer: Yes.'
        request.session['player_knows'][subject] = YES
    else:
        question = 'Computer: No.'
        request.session['player_knows'][subject] = NO
    request.session['questions'].append(question)

    computer_turn(request)

    request.session.modified = True
    return HttpResponseRedirect(reverse('guesswho:play'))

def computer_turn(request):
    request.session.modified = True
    # Check whether we know for sure what the player's character is
    print(request.session['npc_possible'], request.session['char'])
    if len(request.session['npc_possible']) == 1 and \
            request.session['npc_possible'][0] == request.session['char']:
        request.session['questions'].append('Computer is it ' + \
            request.session['npc_possible'][0] + '?')
        request.session['questions'].append('You: Yes')
        request.session['questions'].append('The computer has won')
        request.session['finished'] = True
        return
    # Count the number of traits that are present in the possible characters
    traits = {}
    for c in request.session['npc_possible']:
        for t in characters[c]:
            if request.session['npc_knows'][t] != UNKNOWN:
                continue # Skip traits we already know something about
            try:
                traits[t] += 1
            except KeyError:
                traits[t] = 1
    print(traits)
    # Pick the trait with the highest character count
    trait = max(traits)
    # If there is only one character with a trait max, start guessing
    if traits[trait] == 1:
        char = random.choice(request.session['npc_possible'])
        question = 'Computer: Is it ' + char + '?'
        request.session['questions'].append(question)
        if request.session['char'] == char:
            request.session['questions'].append('You: Yes.')
            request.session['questions'].append('The computer has won')
            request.session['finished'] = True
        else:
            request.session['questions'].append('You: No.')
            request.session['npc_possible'].remove(char)
        return
    # Ask the question about the trait (and update the Kripke model)
    question = 'Computer: ' + get_question_text(trait)
    request.session['questions'].append(question)
    remove = set()
    if trait in characters[request.session['char']]:
        answer = 'You: Yes.'
        request.session['npc_knows'][trait] = YES
        for char in request.session['npc_possible']:
            if trait not in characters[char]:
                remove.add(char)
    else:
        answer = 'You: No.'
        request.session['npc_knows'][trait] = NO
        for char in request.session['npc_possible']:
            if trait in characters[char]:
                remove.add(char)
    request.session['questions'].append(answer)
    for c in remove:
        request.session['npc_possible'].remove(c)

mas/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="https://cdn.muicss.com/mui-0.4.7/css/mui.min.css" rel="stylesheet" type="text/css" />
	<script src="https://cdn.muicss.com/mui-0.4.7/css/mui.min.js"></script>
	<title>{% block title %}{% endblock %}</title>
	<style>
		html, body {
			height: 100%;
		}

		html, body, input, textarea, buttons {
			-webkit-font-smoothing: antialiased;
			-moz-osx-font-smoothing: grayscale;
			text-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.004);
		}

		#sidebar {
			background-color: #E57373;
			padding: 15px;
		}

		@media (min-width: 768px) {
			#sidebar {
				position: fixed;
				top: 0;
				bottom: 0;
				width: 180px;
				height: 100%;
				padding-top: 30px;
			}
		}

		@media (min-width: 768px) {
			#content {
				margin-left: 180px;
			}
		}

		img.grayscale {
			filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
			filter: gray;
			-webkit-filter: grayscale(100%);
		}
	</style>
</head>
<body>

<div id="sidebar">
	<div class="mui--text-light mui--text-display1 mui--align-vertical">Guess Who?</div>
	<div class="mui-divider"></div>
	<ul class="mui-list--unstyled mui--text-title">
		<li><a href="{% url 'guesswho:home' %}" class="mui--text-white">Home</a></li>
		<li><a href="{% url 'guesswho:play' %}" class="mui--text-white">Play</a></li>
	{% block sidebar %}{% endblock %}
	</ul>
</div>
<div id="content" class="mui-container-fluid">
	{% block content %}{% endblock %}
</div>

</body>
</html>

mas/templates/play.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Play Guess Who?{% endblock %}

{% block content %}
{% get_static_prefix as STATIC_PREFIX %}
<div class="mui-row">
	<div class="mui-col-sm-10 mui-col-sm-offset-1">
		<div class="mui--text-dark-secondary mui--text-headline">Instructions</div>
		<div class="mui-divider"></div>
	</div>
	<div class="mui-col-sm-10 mui-col-sm-offset-1">
		<p>Start by picking a character as your identity by clicking a portret.
		The identity of the NPC will be chosen randomly.</p>
		
		<p>After you have picked a character the game board will appear with
		the selection of characters and buttons beneath them. You can ask the
		NPC about its identity by clicking the buttons. The NPC will
		answer the it and it will follow up with its own question, which is
		automatically answered for you. You can also click on one of the
		portraits to make a direct guess at the NPC's identity. The questions
		and answers are displayed in anti-chronological order underneath the
		question buttons.</p>

		<p>You can keep track of what the NPC knows about your identity by
		looking at the truth propositions located to the right of the portrets.
		Your own identity and what the NPC thinks your identity is are
		shown above the game board.</p>
		
		<p>The game is won if you guess the NPC's identity before your
		own is discovered. The game can be reset by pressing the START NEW GAME
		button at the top of the page.</p>
	</div>
</div>
<div class="mui-row">
	<div class="mui-col-sm-offset-1 mui-col-sm-10">
		<a href="{% url 'guesswho:reset' %}" class="mui-btn mui-btn--danger">Start new game</a>
	</div>
</div>

{% if messages %}
	<div class="mui-row">
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
		<ul class="messages">
			{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		</div>
	</div>
{% endif %}

{% if not request.session.char %}
	<div class="mui-row">
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			<div class="mui--text-dark-secondary mui--text-title">
				Pick your character
			</div>
			<div class="mui-divider"></div>
		</div>
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			{% for c in chars %}
				<a href="{% url 'guesswho:char' c %}">
					<img src="{% static c %}.png" />
				</a>
			{% endfor %}
		</div>
	</div>
{% else %}
	<div class="mui-row">
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			<div class="mui--text-dark-secondary mui--text-subhead">
				Knowledge
			</div>
			<div class="mui-divider"></div>
		</div>
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			<div class="mui--text-body2">
				You have picked {{ request.session.char }}. The NPC thinks
				that you are
				{% for c in  request.session.npc_possible %}
					{% if forloop.last and not forloop.first %} or {% endif %}
					{{ c }}{% if not forloop.last %}, {%endif %}
				{% endfor %}.
			</div>
		</div>
		<div class="mui-col-sm-6 mui-col-sm-offset-1">
			{% for c in chars %}
				<a href="{% url 'guesswho:guess' c %}">
				<img src="{{ STATIC_PREFIX }}{{ c }}.png"
					{% if c in exclude %}class="grayscale"{% endif %} />
				</a>
			{% endfor %}
			<br />
		</div>
		<div class="mui-col-sm-2">
			<div class="mui--text-dark-secondary mui--text-caption">
				Computer knows
			</div>
			{% autoescape off %}
				{% for k in npc_knows %}
					{{ k }}</br>
				{% endfor %}
			{% endautoescape %}
		</div>
		<div class="mui-col-sm-2">
			<div class="mui--text-dark-secondary mui--text-caption">
				Computer knows that you know
			</div>
			{% autoescape off %}
				{% for k in player_knows %}
					{{ k }}</br>
				{% endfor %}
			{%endautoescape %}
		</div>
	</div>

	<div class="mui-row">
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			<div class="mui--text-dark-secondary mui--text-subhead">Questions</div>
			<div class="mui-divider"></div>
		</div>
		{% if not request.session.finished %}
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			<a href="{% url 'guesswho:question' 'bald' %}"
				class="mui-btn mui-btn--raised">Is he bald?</a>
			<a href="{% url 'guesswho:question' 'beard' %}"
				class="mui-btn mui-btn--raised">Does he have a beard?</a>
			<a href="{% url 'guesswho:question' 'glasses' %}"
				class="mui-btn mui-btn--raised">Does he wear glasses?</a>
			<a href="{% url 'guesswho:question' 'moustache' %}"
				class="mui-btn mui-btn--raised">Does he have a moustache?</a>
		</div>
		{% endif %}
	</div>

	<div class="mui-row">
		<div class="mui-col-sm-10 mui-col-sm-offset-1">
			{% for question in questions %}
				<div>{{ question }}</div>
			{% endfor %}
		</div>
	</div>
{% endif %}

{% endblock %}